app:
  port: 8080
ws:
  timeout: 10s
  ping-interval: 1s
  read-limit: 64000
  buffer-size: 256
notification-bus:
  redis:
    user-topic: /to/user/
    single:
      host: localhost
      port: 6379
    cluster:
      consul:
        host: localhost
        port: 8500
        redis-service-name: redis-notification-bus
