version: "3.9"
services:
  chat-postgresql:
    image: postgres:14.2
    volumes:
      - ~/volumes/online-chat-go/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=online-chat
      - POSTGRES_PASSWORD=jumanji
      - POSTGRES_DB=online-chat
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
  redis-notification-bus:
    image: redis-notification-bus
    build:
      context: ./notifications/redis_bus
      args:
        CONSUL_VERSION: 1.16.0
    environment:
      CONSUL_HOST: consul-server
    ports:
      - "6379:6379"
  consul-server:
    image: hashicorp/consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -node consul_server -ui -bootstrap -client 0.0.0.0"